# Generated by Django 2.0.5 on 2018-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyyet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyyet',
            name='diapers_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
